config/routes.rb
Rails.application.routes.draw do
  root to: "desks#index"
  
  resources :desks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/desk.rb
class Desk < ApplicationRecord
    validates :content, presence: true, length: {maximum: 255}
    validates :title, presence: true, length: {maximum: 255}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/desks_controller.rb
class DesksController < ApplicationController
    before_action :set_desk, only: [:show, :edit, :update, :destroy]
    
    
    def index
        @desks = Desk.order(id: :desc).page(params[:page]).per(15)
    end
    
    def show
    end
    
    def new
        @desk = Desk.new
    end
    
    def create
        @desk = Desk.new(desk_params)
        
        if @desk.save
            flash[:success] = "Deskは正常に投稿されました"
            redirect_to @desk
        else
            flash[:danger] = "Deskは投稿されませんでした"
            render :new
        end
    end
    
    def edit
    end
    
    def update
        if @desk.update(desk_params)
            flash[:success] = "Deskは正常に編集されました"
            redirect_to @desk
        else
            flash[:danger] = "Deskは編集されませんでした"
            render :edit
        end
    end
    
    def destroy
        @desk.destroy
        
        flash[:success] = "Deskは正常に削除されました"
        redirect_to desks_url
    end
    
    private
    
    def set_desk
        @desk = Desk.find(params[:id])
    end
    
    def desk_params
        params.require(:desk).permit(:content, :title)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/desks/_form.html.erb
<div class="row">
    <div class="col-6">
        <%= form_with(model: desk, local: true) do |f| %>
            <% if desk.errors.any? %>
                <div id="error_explanation" class="alert alert-warning">
                    <ul class="mb-0">
                        <% desk.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            
            <div class="form-group">
                <%= f.label :title, "タイトル" %>
                <%= f.text_field :title, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :content, "デスク名" %>
                <%= f.text_field :content, class: "form-control" %>
            </div>
        
            <%= f.submit "投稿する", class: "btn btn-primary" %>
        <% end %>   
    </div>
</div>

app/views/desks/edit.html.erb
<h1>id: <%= @desk.id %>の編集ページ</h1>

<%= render "form", desk: @desk %>

app/views/desks/index.html.erb
<h1>デスク一覧表示</h1>

<% if @desks.any? %>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>id</th>
                <th>タイトル</th>
                <th>デスク名</th>
            </tr>
        </thead>
        <tbody>
            <% @desks.each do |desk| %>
                <tr>
                    <td><%= link_to desk.id, desk %></td>
                    <td><%= desk.title %></td>
                    <td><%= desk.content %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <div>
        <%= paginate @desks %>
    </div>
<% end %>

<%= link_to "新規投稿", new_desk_path, class: "btn btn-primary" %>

app/views/desks/new.html.erb
<h1>新規デスク作成ページ</h1>

<%= render "form", desk: @desk %>

app/views/desks/show.html.erb
<h1>id: <%= @desk.id %>のデスク詳細ページ</h1>

<table class="table table-bordered">
    <tr>
        <th>id</th>
        <td><%= @desk.id %></td>
    </tr>
    <tr>
        <th>タイトル</th>
        <td><%= @desk.title %></td>
    </tr>
    <tr>
        <th>デスク名</th>
        <td><%= @desk.content %></td>
    </tr>
</table>

<%= link_to "このデスク編集する", edit_desk_path, class: "btn btn-light" %>
<%= link_to "このデスクを削除する", @desk, method: :delete, data: {confirm: "本当に削除してよろしいですか？"}, class: "btn btn-danger" %>

app/views/layouts/_flash_desks.html.erb
<% flash.each do |desk_type, desk| %>
    <div class="alert alert-<%= desk_type %>"><%= desk %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="/">DeskList</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item"><%= link_to "新規デスクの投稿", new_desk_path, class: "nav-link" %></li>
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Desklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    
    <div class="container">
    <%= render "layouts/flash_desks" %>
    
    <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </body>
</html>